[pnnl/gmt#9] C++ porting
pnnl/gmt pull request #10
Opened 2018-05-24 23:30 UTC by droccom

compiles with g++ 7.3, not tested yet

2018-05-24 23:38 UTC, mminutoli commented
@droccom I will wait for the patch set to be tested before reviewing it.

2018-05-25 00:35 UTC, droccom commented
All the tests passing from the C version also pass from the C++ version.

2018-05-31 01:12 UTC, droccom commented
@mminutoli All the tests pass also with multiple nodes, I think you can proceed and review the PR.

2018-05-31 20:57 UTC, mminutoli requested changes

2018-05-31 20:57 UTC, mminutoli commented on src/CMakeLists.txt
> +target_link_libraries(gmt ${MPI_LIBRARIES} pthread)
The build system should be refactored, but that's a task on its own.  Please, change the relevant part into something like this:
```
find_package(Threads REQUIRED)
include_directories(${THREADS_PTHREADS_INCLUDE_DIR})

add_library(gmt ${sources})
target_link_libraries(gmt ${MPI_LIBRARIES} ${CMAKE_THREAD_LIBS_INIT})
```

2018-05-31 20:58 UTC, mminutoli commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -pthread")
Remove -pthread here and use the flag from the comment below.

2018-05-31 21:37 UTC, droccom commented
commit 427954a4eb32d897eddc1c121a141730eb3b846b should clear the review

2018-05-31 21:43 UTC, mminutoli approved these changes

2018-05-31 21:46 UTC, merged